default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: comics_blog_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: comics_blog_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
